spring:
  application:
    name: auth-app
  profiles:
    active: dev

server:
  port: 8083

# JWT Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}

#configurations

#database configurations

#email configurations

#oauth2 configurations